apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: tap-gui-catalog-info
  description: A sample catalog for Backstage
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  targets:
    - ./components/tap-gui.yaml
    - ./components/tdemo1.yaml
    - ./groups/default-org.yaml
    - ./systems/tap-gui-system.yaml
    - ./systems/tdemo1-system.yaml
    - ./domains/tap-gui-domain.yaml
    - ./domain/tdemo1-domain.yaml
